<?php

namespace GaussBundle\Repository;

/**
 * AboIptvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboIptvRepository extends \Doctrine\ORM\EntityRepository
{
}
