<?php

namespace GaussBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCollection(){
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.category != :param order by u.id desc ')
            ->setParameter('param', 5)
            ->setMaxResults(6);
        return $qb->getQuery()->getResult();
    }
}
