homepage:
    path:     /
    defaults: { _controller: GaussBundle:Default:index }

set_local_user:
    path:     /updateLang/{lang}
    defaults: { _controller: GaussBundle:Default:setLocal }

shoppage:
    path:     /shop
    defaults: { _controller: GaussBundle:Shop:index }

homepage_contact:
    path:     /contact
    defaults: { _controller: GaussBundle:Default:contact }

homepage_about:
    path:     /about
    defaults: { _controller: GaussBundle:Default:about }

homepage_404:
    path:     /notFound
    defaults: { _controller: GaussBundle:Default:notFound }

shoppage_category:
    path:     /shop/{id_categ}
    defaults: { _controller: GaussBundle:Shop:indexCateg }
    requirements:
        id_categ: \d+
adminpage:
    path:     /admin
    defaults: { _controller: GaussBundle:Admin:index }

adminpage_add_product:
    path:     /admin/addProduct
    defaults: { _controller: GaussBundle:AdminProduct:addProduct }

adminpage_list_product:
    path:     /Shop/allProducts
    defaults: { _controller: GaussBundle:AdminProduct:listProduct }
adminpage_list_users:
    path:     /Shop/allUsers
    defaults: { _controller: GaussBundle:Admin:listUser }

adminpage_enable_users:
    path:     /Shop/allUsers/enable/{id_user}
    defaults: { _controller: GaussBundle:Admin:enable }
    requirements:
        id_user: \d+
adminpage_disable_users:
    path:     /Shop/allUsers/disable/{id_user}
    defaults: { _controller: GaussBundle:Admin:disable }
    requirements:
        id_user: \d+

adminpage_view_product:
    path:     /Shop/viewProduct/{id_product}
    defaults: { _controller: GaussBundle:Shop:viewProduct }
    requirements:
        id_product: \d+

adminpage_add_category:
    path:     /admin/addCategory
    defaults: { _controller: GaussBundle:AdminCategory:addCategory }

adminpage_list_category:
    path:     /admin/allCategory
    defaults: { _controller: GaussBundle:AdminCategory:listCategory }

adminpage_view_cart:
    path:     /Shop/viewCart
    defaults: { _controller: GaussBundle:Panier:viewCart }

adminpage_add_to_cart:
    path:     /Shop/addToCart/{id_product}
    defaults: { _controller: GaussBundle:Panier:addToCart }
    requirements:
        id_product: \d+

adminpage_delete_from_cart:
    path:     /Shop/deleteFromCart/{id_product}
    defaults: { _controller: GaussBundle:Panier:deleteFromCart }
    requirements:
        id_product: \d+

shoppage_wishlist:
    path:     /WishList
    defaults: { _controller: GaussBundle:Wish:index }

adminpage_add_to_wish:
    path:     /Shop/addToWish/{id_product}
    defaults: { _controller: GaussBundle:Wish:addToWish }
    requirements:
        id_product: \d+

adminpage_delete_from_wish:
    path:     /Shop/deleteFromWish/{id_product}
    defaults: { _controller: GaussBundle:Wish:deleteFromWish }
    requirements:
        id_product: \d+
adminpage_add_aboiptv:
    path:     /admin/addAboIptv
    defaults: { _controller: GaussBundle:AdminProduct:addIptv }

adminpage_list_aboIptv:
    path:     /admin/allAboIptv
    defaults: { _controller: GaussBundle:AdminProduct:listIptv }

shoppage_list_aboIptv:
    path:     /Shop/allAboIptv
    defaults: { _controller: GaussBundle:Iptv:index }

shoppage_center:
    path:     /Shop/downloadCenter
    defaults: { _controller: GaussBundle:Iptv:center }